### ISSUE TITLE
Task doesn't work???

### ISSUE THREAD

**Issue by tandrewnichols** [MrBoolean/grunt-codeclimate-reporter#5]
When I run this task, both locally and on travis, I get the following:

```
Unhandled rejection Error: true
    at maybeWrapAsError (/Users/AndrewNichols/code/anichols/grunt-only/node_modules/grunt-codeclimate-reporter/node_modules/bluebird/js/main/util.js:70:12)
    at /Users/AndrewNichols/code/anichols/grunt-only/node_modules/grunt-codeclimate-reporter/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at FSReqWrap.cb [as oncomplete] (fs.js:226:19)
```

My configuration in Gruntfile.js looks like this:

``` js
    codeclimate: {
      main: {
        options: {
          file: 'coverage/coverage.lcov',
          token: 'd7abe4f421d4b39b0618b3f8d75d112e7e2d347837ad33e4a94b1be8ab57ccca'
        }
      }
    },
```

**Comment by Xiphe** [comment]
pr inc

**Comment by christian-meyer-jimdo** [comment]
:+1:

**Comment by Xiphe** [comment]
Should be fixed with current master.
@MrBoolean : would be great if you could publish a new version soon :)

**Comment by m19c** [comment]
@Xiphe: :+1:  Thanks for your help!
